import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';

/// Adds a new locale/language to a Flutter project
/// generated by the Codeable CLI.
class AddLocaleCommand extends Command<int> {
  AddLocaleCommand({required Logger logger}) : _logger = logger {
    argParser.addOption(
      'locale',
      abbr: 'l',
      help: 'The locale code (e.g., fr, de, ar, pt_BR).',
    );
  }

  final Logger _logger;

  @override
  String get description => 'Add a new locale/language to the project.';

  @override
  String get name => 'add-locale';

  @override
  String get invocation =>
      'codeable_cli add-locale --locale <locale_code>';

  @override
  Future<int> run() async {
    // Ensure we're inside a Flutter project
    final pubspecFile = File('pubspec.yaml');
    if (!pubspecFile.existsSync()) {
      _logger.err(
        'No pubspec.yaml found. '
        'Run this command from inside a Flutter project.',
      );
      return ExitCode.usage.code;
    }

    // Get locale code
    var locale = argResults?['locale'] as String?;
    if (locale == null || locale.isEmpty) {
      locale = _logger.prompt(
        'What locale would you like to add? (e.g., fr, de, ar, pt_BR)',
      );
    }

    // Validate locale code (2-letter ISO 639-1, optionally with country code)
    if (!_isValidLocaleCode(locale)) {
      _logger.err(
        'Invalid locale code "$locale". '
        'Use a 2-letter ISO 639-1 code (e.g., fr, de) '
        'or with a country code (e.g., pt_BR, zh_CN).',
      );
      return ExitCode.usage.code;
    }

    // Check that l10n/arb directory exists
    final arbDir = Directory('lib/l10n/arb');
    if (!arbDir.existsSync()) {
      _logger.err(
        'Directory lib/l10n/arb/ not found. '
        'Is this a Codeable CLI project with localization set up?',
      );
      return ExitCode.software.code;
    }

    // Check that the ARB file doesn't already exist
    final newArbFile = File('lib/l10n/arb/app_$locale.arb');
    if (newArbFile.existsSync()) {
      _logger.err(
        'ARB file for locale "$locale" already exists at '
        '${newArbFile.path}. Nothing to do.',
      );
      return ExitCode.usage.code;
    }

    _logger
      ..info('')
      ..info(
        'Adding locale ${lightCyan.wrap(locale)} '
        'to the project...',
      )
      ..info('');

    // Step 1: Read existing English ARB as reference
    final readProgress = _logger.progress('Reading English ARB reference');
    final enArbFile = File('lib/l10n/arb/app_en.arb');
    if (!enArbFile.existsSync()) {
      readProgress.fail('English ARB file not found');
      _logger.err(
        'Could not find lib/l10n/arb/app_en.arb. '
        'An English ARB file is required as a reference.',
      );
      return ExitCode.software.code;
    }

    final Map<String, dynamic> enArb;
    try {
      enArb = jsonDecode(enArbFile.readAsStringSync())
          as Map<String, dynamic>;
    } on FormatException catch (e) {
      readProgress.fail('Failed to parse English ARB');
      _logger.err('Could not parse app_en.arb: $e');
      return ExitCode.software.code;
    }
    readProgress.complete('English ARB loaded (${enArb.length} entries)');

    // Step 2: Create new ARB file
    final createProgress = _logger.progress('Creating app_$locale.arb');
    final newArb = <String, dynamic>{};

    for (final entry in enArb.entries) {
      final key = entry.key;
      final value = entry.value;

      if (key == '@@locale') {
        // Set locale to the new locale
        newArb[key] = locale;
      } else if (key.startsWith('@')) {
        // Preserve all @key metadata entries as-is
        newArb[key] = value;
      } else {
        // Regular translation key — set placeholder value
        newArb[key] = '[TODO: $locale] $value';
      }
    }

    try {
      const encoder = JsonEncoder.withIndent('  ');
      newArbFile.writeAsStringSync(
        '${encoder.convert(newArb)}\n',
      );
    } on FileSystemException catch (e) {
      createProgress.fail('Failed to create ARB file');
      _logger.err('Could not write app_$locale.arb: $e');
      return ExitCode.software.code;
    }
    createProgress.complete('Created lib/l10n/arb/app_$locale.arb');

    // Step 3: Verify l10n.yaml configuration
    final l10nProgress = _logger.progress('Verifying l10n.yaml');
    final l10nFile = File('l10n.yaml');
    if (l10nFile.existsSync()) {
      final l10nContent = l10nFile.readAsStringSync();
      if (l10nContent.contains('arb-dir')) {
        l10nProgress.complete(
          'l10n.yaml uses arb-dir — new locale will be auto-detected',
        );
      } else {
        l10nProgress.complete(
          'l10n.yaml found (verify locale configuration manually)',
        );
      }
    } else {
      l10nProgress.complete('No l10n.yaml found — skipping verification');
    }

    // Step 4: Run flutter gen-l10n
    final genL10nProgress = _logger.progress('Running flutter gen-l10n');
    final genL10nResult = await Process.run(
      'flutter',
      ['gen-l10n'],
    );

    if (genL10nResult.exitCode != 0) {
      genL10nProgress.fail('flutter gen-l10n failed');
      _logger
        ..err(genL10nResult.stderr.toString())
        ..warn(
          'The ARB file was created but code generation '
          'failed. Fix any errors and run '
          '"flutter gen-l10n" manually.',
        );
    } else {
      genL10nProgress.complete('Localization classes regenerated');
    }

    _logger
      ..info('')
      ..success('Locale "$locale" added successfully!')
      ..info('')
      ..info(
        'New ARB file: '
        '${lightCyan.wrap('lib/l10n/arb/app_$locale.arb')}',
      )
      ..info('')
      ..info('Next steps:')
      ..info(
        '  1. Replace all ${lightYellow.wrap('[TODO: $locale]')} placeholders '
        'with actual translations.',
      )
      ..info(
        '  2. If your app does not auto-detect supported locales, add '
        '${lightCyan.wrap("Locale('$locale')")} to '
        '${lightCyan.wrap('supportedLocales')} in your MaterialApp.',
      )
      ..info('');

    return ExitCode.success.code;
  }

  /// Validates a locale code.
  /// Accepts 2-letter codes (e.g., fr, de) and codes with a country
  /// suffix (e.g., pt_BR, zh_CN).
  bool _isValidLocaleCode(String code) {
    return RegExp(r'^[a-z]{2}(_[A-Z]{2})?$').hasMatch(code);
  }
}
